### ISSUE TITLE
Accessibility link in footer to meet 508 Compliance required by NASA

### ISSUE THREAD

**Issue by cowen23** [nasa/meza#46]
### Environment

- VMware virtual machine - Machine or Virtual Machine details: (VirtualBox, VMWare, Digital Ocean, AWS, etc)
- redhat-release-eula-8.9-0.1.el8.x86_64 - Operating System: (run `cat /etc/redhat-release` and report output)
- a38b6e0 - meza version hash: (run `cd /opt/meza && git rev-parse --short HEAD` and report output)

### Issue details

Agency-IT-Outreach sent email on 3/12/24 from Chief Information Officer stating all NASA web sites, both internal and external require a link to NASA's accessibility statement, located at https://www.nasa.gov/accessibility/ in the footer.

One solution could be to:
1.  Add the following to the localsettings.php page:
$wgHooks['SkinAddFooterLinks'][] = function ( Skin $skin, string $key, array &$footerlinks ) {
    if ( $key === 'places' ) {
        $footerlinks['508link'] = Html::rawElement( 'a',['href' => 'https://www.nasa.gov/accessibility/','rel' => 'noreferrer noopener'],$skin->msg( 'Accessibility-link' )->text());
    };
};

2. Then create a new page at https://<web site>/index.php?title=MediaWiki:Accessibility-link and just drop the word ‘Accessibility’ in it.

**Comment by ndc-rkevans** [comment]
fixed in 39.x with https://github.com/nasa/meza/commit/1697c20fcf34866bf92bc816091e98546d4d1fe0

**Comment by ndc-rkevans** [comment]
fixed in 39.x with https://github.com/nasa/meza/commit/1697c20fcf34866bf92bc816091e98546d4d1fe0
