### ISSUE TITLE
Could not connect to mirror.centos.org error is always presented

### ISSUE THREAD

**Issue by bunnypranav** [nasa/meza#57]
### Environment

- Machine or Virtual Machine details: Proxmox VM
- Operating System: Rocky Linux release 8.10 (Green Obsidian)

### Issue details

While running `bash /opt/meza/src/scripts/getmeza.sh`, I get an error saying _Could not connect to mirror.centos.org. Internet Connection might be down_. I am sure I have a working internet connection, tested using installing any package (eg. `yum install git`). Removing the `checkInternetConnection()` portion from getmeza.sh fixes the issue, but many errors are presented. 
```
CentOS Configmanagement SIG - ansible-29                                                                                    0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'centos-ansible-29':
  - Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=configmanagement-ansible-29 [Could not resolve host: mirrorlist.centos.org]
Error: Failed to download metadata for repo 'centos-ansible-29': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=configmanagement-ansible-29 [Could not resolve host: mirrorlist.centos.org]
CentOS Configmanagement SIG - ansible-29                                                                                    0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'centos-ansible-29':
  - Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=configmanagement-ansible-29 [Could not resolve host: mirrorlist.centos.org]
Error: Failed to download metadata for repo 'centos-ansible-29': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=configmanagement-ansible-29 [Could not resolve host: mirrorlist.centos.org]
CentOS Configmanagement SIG - ansible-29                                                                                    0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'centos-ansible-29':
  - Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=configmanagement-ansible-29 [Could not resolve host: mirrorlist.centos.org]
Error: Failed to download metadata for repo 'centos-ansible-29': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=configmanagement-ansible-29 [Could not resolve host: mirrorlist.centos.org]
CentOS Configmanagement SIG - ansible-29                                                                                    0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'centos-ansible-29':
  - Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=configmanagement-ansible-29 [Could not resolve host: mirrorlist.centos.org]
Error: Failed to download metadata for repo 'centos-ansible-29': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=configmanagement-ansible-29 [Could not resolve host: mirrorlist.centos.org]
/usr/bin/python3 has not been configured as an alternative for python
```
With Centos 8 being gone, mirror will always be down, the code should be changed to reflect this
Thanks!

**Comment by revansx** [comment]
Are you using the main branch? Does your version of getmeza.py have this commit: https://github.com/nasa/meza/commit/ba25a5df5f98b1911ca9e8c82d49915ec3837549

**Comment by bunnypranav** [comment]
I used these lines from the [https://www.mediawiki.org/wiki/Meza/Install_on_existing_server](https://www.mediawiki.org/wiki/Meza/Install_on_existing_server)

```
export MEZA_REPOSITORY_URL='https://github.com/nasa/meza.git'
export MEZA_BRANCH_NAME='39.x'
git clone --branch $MEZA_BRANCH_NAME $MEZA_REPOSITORY_URL /opt/meza
```

**Comment by revansx** [comment]
Apologies, that documentation is out-of-date

Here's a link to a site where I have chronicled my notes on installing Meza onto a fresh new RL8 server:
https://meza.wiki/meza

**Comment by bunnypranav** [comment]
Thanks, will definitely check it out.

**Comment by bunnypranav** [comment]
Hi @revansx

I tried your documenttion, but am still getting an error. Below is a terminal output
``` bash
[root@localhost meza]# git status
On branch main
Your branch is up to date with 'origin/main'.
nothing to commit, working tree clean
[root@localhost meza]# bash /opt/meza/src/scripts/getmeza.sh
Could not connect to mirrorlist.centos.org. Internet connection might be down. Retrying (#100) in 3 seconds...
Could not connect to mirrorlist.centos.org. Internet connection might be down. Retrying (#99) in 3 seconds...
Could not connect to mirrorlist.centos.org. Internet connection might be down. Retrying (#98) in 3 seconds...
^C
[root@localhost meza]#
```

**Comment by revansx** [comment]
I'm sorry you're having issues. 

Did you start over entirely with a fresh system?

I'm on holiday for another week, but plan to addresses this when I get back. 

In the meantime, try installing git and ansible manually before running grtmeza.py

sudo dnf install git

sudo dnf install ansible 

Then run getmeza.py

**Comment by cowen23** [comment]
FYI -

I ran into this error also back in July.

This is happening because the <install-dir>/meza/src/scripts/getmeza.sh is trying to ping mirrorlist.centos.org to verify the internet connection is good.  However, the url mirrorlist.centos.org is no longer a valid website.
See  https://github.com/nasa/meza/blob/39.x/src/scripts/getmeza.sh#L22

I edited lines in the <install-dir>/meza/src/sripts/getmeza.sh on my system from:
        while [[ $pingRetries -gt 0 ]] && ! ping -c 1 -W 1 mirrorlist.centos.org >/dev/null 2>&1; do
                echo "Could not connect to mirrorlist.centos.org. Internet connection might be down. Retrying (#$pingRetries) in $sleepDuration seconds..."
to:
        while [[ $pingRetries -gt 0 ]] && ! ping -c 1 -W 1 cdn.redhat.com >/dev/null 2>&1; do
                echo "Could not connect to cdn.redhat.com. Internet connection might be down. Retrying (#$pingRetries) in $sleepDuration seconds..."

Then it runs fine.

Respectfully,
Carolyn R. Owen
Systems Administrator IV
AEGIS
228.688.2526
***@***.******@***.***>

From: Rich Evans ***@***.***>
Sent: Thursday, October 31, 2024 1:18 AM
To: nasa/meza ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [nasa/meza] Could not connect to mirror.centos.org error is always presented (Issue #57)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



I'm sorry you're having issues.

Did you start over entirely with a fresh system?

I'm on holiday for another week, but plan to addresses this when I get back.

In the meantime, try installing git and ansible manually before running grtmeza.py

sudo dnf install git

sudo dnf install ansible

Then run getmeza.py

-

**Comment by bunnypranav** [comment]
@cowen23 Thanks for the tip, this solved the issue. Hope the team can implement this fix in the script as well.

**Comment by bunnypranav** [comment]
@amcgillivray-nasa Thanks for the pull request. @revansx I think installation of Jinja2 needs to be added, as that was not done for my testing
